### ISSUE TITLE
Occasional test failures due to lack of 'server-timing' key

### ISSUE THREAD

**Issue by VxJasonxV** [martinbrose/cloudflare-speedtest-exporter#1]
I have a Grafana Dashboard that graphs results from this test in multiple network locations and once in a while I notice that a speedtest run was missed leaving a data gap.

These logs appear to list both the test error and the metric export error, presumably only the first half matters:

```
Traceback (most recent call last):
  File "/usr/local/bin/cfspeedtest", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/cloudflarepycli/__main__.py", line 35, in main
    thedict=thetester.runalltests()
  File "/usr/local/lib/python3.10/site-packages/cloudflarepycli/cloudflareclass.py", line 152, in runalltests
    fulltimes,servertimes,requesttimes=self.download(1,self.latencyreps) #measure latency and jitter
  File "/usr/local/lib/python3.10/site-packages/cloudflarepycli/cloudflareclass.py", line 114, in download
    servertimes=servertimes+(float(r.headers['Server-Timing'].split('=')[1])/1e3,)
  File "/usr/local/lib/python3.10/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'server-timing'
level=ERROR datetime=2022-11-24 08:33:56,540 Exception on /metrics [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/exporter.py", line 112, in updateResults
    logging.info("Server City=" + r_server_city + " Server Region=" + r_server_region +
TypeError: can only concatenate str (not "int") to str
```

**Comment by martinbrose** [comment]
Hi @VxJasonxV, thanks for posting this issue.

On first glance it looks like the Cloudflare Speedtest is failing for some reason . 
I'll spin up some instances and see if I can replicate it this week.

**Comment by martinbrose** [comment]
Did you change the version of cloudflarepycli from 1.0.3 to a higher one by any chance?

I can replicate your problem if I upgrade cloudflarepycli to 1.7.0.

**Comment by VxJasonxV** [comment]
Hum. I'm running this via Docker (Compose) and I specify `redorbluepill/cloudflare-speedtest-exporter` as the image. I just looked at its requirements.txt file and it is also pinned to ==1.0.3

Because it's in Docker nothing about the inner environment has changed in 7 months ( https://hub.docker.com/r/redorbluepill/cloudflare-speedtest-exporter/tags ).

I run two instances of that container on two different hosts at two different points of my network, the test on each runs every half hour. (I can probably turn one of them off because the two points of my network are consistent. I ruled out any sort of bad behavior of a switch or cable or other network nuisance…)

Between the two of them it's happening multiple times a day, they never run at the exact same time, they always stagger surprisingly well, with at least a 5-10 minute buffer between them.

Is there a flag or env or something I can turn on to increase the debug level and get more details? Or something else I can do to get further details?

What is/isn't happening to cause this error? I've used the speed test webpage manually a few times so I have a reasonably good mental image of what all the output is supposed to be.

(Aside: Nothing to do with your work, but I just noticed in my successful logs sometimes I test against a Dallas server? I don't live in Texas. Weird.)

**Comment by martinbrose** [comment]
Hi @VxJasonxV, 

thanks for confirming. My current theory is that cloudflarepycli encounters some sort of server error and reports that back.
Do you mind sharing the Cloudflare speedtest servers that are usually been used in the location with the missing speed tests, so I can narrow it down to Cloudflare server issues?

Overall, I seem to have been sloppy in error catching and hence the exporter has this behaviour.
I'll need to update the exporter to actually return the error from cloudflarepycli or write an error log. 
And maybe it should just re-run the test in these cases.
I'll look into this the next couple of days.

**Comment by martinbrose** [comment]
I think I know what the problem was. I overlooked the dependency on Beautiful Soup 4 in getisp() in cloudflarepycli.

I have updated the requirements.txt accordingly.

I have also updated the docker container. So please just pull that one and let me know if the problem shows up again.

**Comment by martinbrose** [comment]
I believe I might have addressed this now. I also updated to cloudflarepycli 1.7.0.

I have updated the Docker container. So please pull and check if the problem shows up again.

**Comment by VxJasonxV** [comment]
Updated, confirmed running cloudflarepycli 1.7.0, my current container IDs are `e49581e3e09b` and `9cecaab9efe5` (only relevant to me, but useful for me). If I don't get back to this issue in 3 days, it's probably safe to close it!
